version: "3"

services:
  web:
      container_name : myslink
      restart: always
      build: .
      ports: 
            - "3000:3000"
      links:
            - mongo
      volumes:
            - .:/usr/src/app
  mongo:
      container_name : mymongomyslink2
      image: mongo
      ports:
            - "27017:27017"
      logging:
            driver: none